return {
  "nvimdev/lspsaga.nvim",
  event = "LspAttach",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
  opts = {},
  cond = not vim.g.vscode,
  keys = {
    { "gd", "<CMD>Lspsaga goto_definition<CR>", { silent = true } },
    {
      "<C-w>gd",
      ":rightbelow vsplit | Lspsaga goto_definition<CR>",
      { silent = true },
    },
    { "gt", "<CMD>Lspsaga goto_type_definition<CR>", { silent = true } },
    {
      "<C-w>gt",
      ":rightbelow vsplit | Lspsaga goto_type_definition<CR>",
      { silent = true },
    },
    { "ca", "<CMD>Lspsaga code_action<CR>", { silent = true } },
    { "<leader>o", "<CMD>Lspsaga outline<CR>", { silent = true } },
    { "K", "<CMD>Lspsaga hover_doc<CR>", { silent = true } },
    { "<leader>cr", "<CMD>Lspsaga rename<CR>", { silent = true } },
    { "<leader>sl", "<CMD>Lspsaga show_line_diagnostics<CR>", { silent = true } },
    { "<leader>sc", "<CMD>Lspsaga show_cursor_diagnostics<CR>", { silent = true } },
    { "<leader>sb", "<CMD>Lspsaga show_buf_diagnostics<CR>", { silent = true } },
    { "<leader>sw", "<CMD>Lspsaga show_workspace_diagnostics<CR>", { silent = true } },
    { "<leader>dp", "<CMD>Lspsaga diagnostic_jump_prev<CR>", { silent = true } },
    { "<leader>dn", "<CMD>Lspsaga diagnostic_jump_next<CR>", { silent = true } },
    { "g]", "<CMD>Lspsaga peek_definition<CR>", { silent = true } },
    { "gt]", "<CMD>Lspsaga peek_type_definition<CR>", { silent = true } },
    { mode = { "n", "t" }, "<A-d>", "<cmd>Lspsaga term_toggle<CR>", { silent = true } },
    { "gi", "<CMD>Lspsaga finder imp<CR>", { silent = true } },
  },
}
